steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_DEPLOY_REGION-$_GCR_HOSTNAME/$PROJECT_ID/gcptest/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_DEPLOY_REGION-$_GCR_HOSTNAME/$PROJECT_ID/gcptest/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push